/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.mifos.creditbureau.connector.circulodecredito.model.CatalogoEstados;
import org.mifos.creditbureau.connector.circulodecredito.model.CatalogoTipoAsentamiento;
import org.mifos.creditbureau.connector.circulodecredito.model.CatalogoTipoDomicilio;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Domicilio
 */
public class DomicilioTest {
    private final Domicilio model = new Domicilio();

    /**
     * Model tests for Domicilio
     */
    @Test
    public void testDomicilio() {
        // TODO: test Domicilio
    }

    /**
     * Test the property 'direccion'
     */
    @Test
    public void direccionTest() {
        // TODO: test direccion
    }

    /**
     * Test the property 'coloniaPoblacion'
     */
    @Test
    public void coloniaPoblacionTest() {
        // TODO: test coloniaPoblacion
    }

    /**
     * Test the property 'delegacionMunicipio'
     */
    @Test
    public void delegacionMunicipioTest() {
        // TODO: test delegacionMunicipio
    }

    /**
     * Test the property 'ciudad'
     */
    @Test
    public void ciudadTest() {
        // TODO: test ciudad
    }

    /**
     * Test the property 'estado'
     */
    @Test
    public void estadoTest() {
        // TODO: test estado
    }

    /**
     * Test the property 'CP'
     */
    @Test
    public void CPTest() {
        // TODO: test CP
    }

    /**
     * Test the property 'fechaResidencia'
     */
    @Test
    public void fechaResidenciaTest() {
        // TODO: test fechaResidencia
    }

    /**
     * Test the property 'numeroTelefono'
     */
    @Test
    public void numeroTelefonoTest() {
        // TODO: test numeroTelefono
    }

    /**
     * Test the property 'tipoDomicilio'
     */
    @Test
    public void tipoDomicilioTest() {
        // TODO: test tipoDomicilio
    }

    /**
     * Test the property 'tipoAsentamiento'
     */
    @Test
    public void tipoAsentamientoTest() {
        // TODO: test tipoAsentamiento
    }

    /**
     * Test the property 'fechaRegistroDomicilio'
     */
    @Test
    public void fechaRegistroDomicilioTest() {
        // TODO: test fechaRegistroDomicilio
    }

    /**
     * Test the property 'tipoAltaDomicilio'
     */
    @Test
    public void tipoAltaDomicilioTest() {
        // TODO: test tipoAltaDomicilio
    }

    /**
     * Test the property 'idDomicilio'
     */
    @Test
    public void idDomicilioTest() {
        // TODO: test idDomicilio
    }

}
