/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.mifos.creditbureau.connector.circulodecredito.model.Domicilio;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestScoreDGPersona
 */
public class RequestScoreDGPersonaTest {
    private final RequestScoreDGPersona model = new RequestScoreDGPersona();

    /**
     * Model tests for RequestScoreDGPersona
     */
    @Test
    public void testRequestScoreDGPersona() {
        // TODO: test RequestScoreDGPersona
    }

    /**
     * Test the property 'nombres'
     */
    @Test
    public void nombresTest() {
        // TODO: test nombres
    }

    /**
     * Test the property 'segundoNombre'
     */
    @Test
    public void segundoNombreTest() {
        // TODO: test segundoNombre
    }

    /**
     * Test the property 'apellidoPaterno'
     */
    @Test
    public void apellidoPaternoTest() {
        // TODO: test apellidoPaterno
    }

    /**
     * Test the property 'apellidoMaterno'
     */
    @Test
    public void apellidoMaternoTest() {
        // TODO: test apellidoMaterno
    }

    /**
     * Test the property 'apellidoAdicional'
     */
    @Test
    public void apellidoAdicionalTest() {
        // TODO: test apellidoAdicional
    }

    /**
     * Test the property 'fechaNacimiento'
     */
    @Test
    public void fechaNacimientoTest() {
        // TODO: test fechaNacimiento
    }

    /**
     * Test the property 'RFC'
     */
    @Test
    public void RFCTest() {
        // TODO: test RFC
    }

    /**
     * Test the property 'CURP'
     */
    @Test
    public void CURPTest() {
        // TODO: test CURP
    }

    /**
     * Test the property 'nacionalidad'
     */
    @Test
    public void nacionalidadTest() {
        // TODO: test nacionalidad
    }

    /**
     * Test the property 'residencia'
     */
    @Test
    public void residenciaTest() {
        // TODO: test residencia
    }

    /**
     * Test the property 'estadoCivil'
     */
    @Test
    public void estadoCivilTest() {
        // TODO: test estadoCivil
    }

    /**
     * Test the property 'sexo'
     */
    @Test
    public void sexoTest() {
        // TODO: test sexo
    }

    /**
     * Test the property 'claveElectorIFE'
     */
    @Test
    public void claveElectorIFETest() {
        // TODO: test claveElectorIFE
    }

    /**
     * Test the property 'numeroDependientes'
     */
    @Test
    public void numeroDependientesTest() {
        // TODO: test numeroDependientes
    }

    /**
     * Test the property 'fechaDefuncion'
     */
    @Test
    public void fechaDefuncionTest() {
        // TODO: test fechaDefuncion
    }

    /**
     * Test the property 'domicilio'
     */
    @Test
    public void domicilioTest() {
        // TODO: test domicilio
    }

}
