/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestScoreFolio
 */
public class RequestScoreFolioTest {
    private final RequestScoreFolio model = new RequestScoreFolio();

    /**
     * Model tests for RequestScoreFolio
     */
    @Test
    public void testRequestScoreFolio() {
        // TODO: test RequestScoreFolio
    }

    /**
     * Test the property 'folioConsulta'
     */
    @Test
    public void folioConsultaTest() {
        // TODO: test folioConsulta
    }

    /**
     * Test the property 'folioOtorgante'
     */
    @Test
    public void folioOtorganteTest() {
        // TODO: test folioOtorgante
    }

}
