/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseScoreScore
 */
public class ResponseScoreScoreTest {
    private final ResponseScoreScore model = new ResponseScoreScore();

    /**
     * Model tests for ResponseScoreScore
     */
    @Test
    public void testResponseScoreScore() {
        // TODO: test ResponseScoreScore
    }

    /**
     * Test the property 'nombreScore'
     */
    @Test
    public void nombreScoreTest() {
        // TODO: test nombreScore
    }

    /**
     * Test the property 'valor'
     */
    @Test
    public void valorTest() {
        // TODO: test valor
    }

    /**
     * Test the property 'razones'
     */
    @Test
    public void razonesTest() {
        // TODO: test razones
    }

}
