version: '3.8'
services:
  mariadb:
    image: mariadb:11.2
    container_name: creditbureau_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysql
      MARIADB_DATABASE: creditbureau
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data: