version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: fineract_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: