/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.api;

import org.mifos.creditbureau.connector.circulodecredito.ApiException;
import org.mifos.creditbureau.connector.circulodecredito.model.Errores;
import org.mifos.creditbureau.connector.circulodecredito.model.RequestScoreFolio;
import org.mifos.creditbureau.connector.circulodecredito.model.ResponseScore;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScoreFolioApi
 */
@Disabled
public class ScoreFolioApiTest {

    private final ScoreFolioApi api = new ScoreFolioApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void folioTest() throws ApiException {
        String xSignature = null;
        String xApiKey = null;
        String username = null;
        String password = null;
        RequestScoreFolio scoreFolio = null;
        ResponseScore response = api.folio(xSignature, xApiKey, username, password, scoreFolio);
        // TODO: test validations
    }

}
