/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.mifos.creditbureau.connector.circulodecredito.model.RequestScoreDGFolio;
import org.mifos.creditbureau.connector.circulodecredito.model.RequestScoreDGPersona;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.creditbureau.connector.circulodecredito.JSON;

/**
 * Cuerpo de la petición para obtener respuesta del servicio
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-04T16:05:43.760511-04:00[America/New_York]", comments = "Generator version: 7.14.0")
public class RequestScoreDG {
  public static final String SERIALIZED_NAME_FOLIO = "folio";
  @SerializedName(SERIALIZED_NAME_FOLIO)
  @javax.annotation.Nonnull
  private RequestScoreDGFolio folio;

  public static final String SERIALIZED_NAME_PERSONA = "persona";
  @SerializedName(SERIALIZED_NAME_PERSONA)
  @javax.annotation.Nonnull
  private RequestScoreDGPersona persona;

  public RequestScoreDG() {
  }

  public RequestScoreDG folio(@javax.annotation.Nonnull RequestScoreDGFolio folio) {
    this.folio = folio;
    return this;
  }

  /**
   * Get folio
   * @return folio
   */
  @javax.annotation.Nonnull
  public RequestScoreDGFolio getFolio() {
    return folio;
  }

  public void setFolio(@javax.annotation.Nonnull RequestScoreDGFolio folio) {
    this.folio = folio;
  }


  public RequestScoreDG persona(@javax.annotation.Nonnull RequestScoreDGPersona persona) {
    this.persona = persona;
    return this;
  }

  /**
   * Get persona
   * @return persona
   */
  @javax.annotation.Nonnull
  public RequestScoreDGPersona getPersona() {
    return persona;
  }

  public void setPersona(@javax.annotation.Nonnull RequestScoreDGPersona persona) {
    this.persona = persona;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestScoreDG requestScoreDG = (RequestScoreDG) o;
    return Objects.equals(this.folio, requestScoreDG.folio) &&
        Objects.equals(this.persona, requestScoreDG.persona);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folio, persona);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestScoreDG {\n");
    sb.append("    folio: ").append(toIndentedString(folio)).append("\n");
    sb.append("    persona: ").append(toIndentedString(persona)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("folio", "persona"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("folio", "persona"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RequestScoreDG
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RequestScoreDG.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestScoreDG is not found in the empty JSON string", RequestScoreDG.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RequestScoreDG.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RequestScoreDG` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestScoreDG.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `folio`
      RequestScoreDGFolio.validateJsonElement(jsonObj.get("folio"));
      // validate the required field `persona`
      RequestScoreDGPersona.validateJsonElement(jsonObj.get("persona"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestScoreDG.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestScoreDG' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestScoreDG> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestScoreDG.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestScoreDG>() {
           @Override
           public void write(JsonWriter out, RequestScoreDG value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestScoreDG read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RequestScoreDG given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RequestScoreDG
   * @throws IOException if the JSON string is invalid with respect to RequestScoreDG
   */
  public static RequestScoreDG fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestScoreDG.class);
  }

  /**
   * Convert an instance of RequestScoreDG to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

