/*
 * FICO® Score
 * <p>La API de FICO® Score determina la probabilidad de incumplimiento de un acreditado en los próximos doce meses. A mayor puntaje de score, menor es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.creditbureau.connector.circulodecredito.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.creditbureau.connector.circulodecredito.JSON;

/**
 * ResponseScoreScore
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-04T16:05:43.760511-04:00[America/New_York]", comments = "Generator version: 7.14.0")
public class ResponseScoreScore {
  public static final String SERIALIZED_NAME_NOMBRE_SCORE = "nombreScore";
  @SerializedName(SERIALIZED_NAME_NOMBRE_SCORE)
  @javax.annotation.Nullable
  private String nombreScore;

  public static final String SERIALIZED_NAME_VALOR = "valor";
  @SerializedName(SERIALIZED_NAME_VALOR)
  @javax.annotation.Nullable
  private Integer valor;

  public static final String SERIALIZED_NAME_RAZONES = "razones";
  @SerializedName(SERIALIZED_NAME_RAZONES)
  @javax.annotation.Nullable
  private List<String> razones = new ArrayList<>();

  public ResponseScoreScore() {
  }

  public ResponseScoreScore nombreScore(@javax.annotation.Nullable String nombreScore) {
    this.nombreScore = nombreScore;
    return this;
  }

  /**
   * Get nombreScore
   * @return nombreScore
   */
  @javax.annotation.Nullable
  public String getNombreScore() {
    return nombreScore;
  }

  public void setNombreScore(@javax.annotation.Nullable String nombreScore) {
    this.nombreScore = nombreScore;
  }


  public ResponseScoreScore valor(@javax.annotation.Nullable Integer valor) {
    this.valor = valor;
    return this;
  }

  /**
   * Get valor
   * @return valor
   */
  @javax.annotation.Nullable
  public Integer getValor() {
    return valor;
  }

  public void setValor(@javax.annotation.Nullable Integer valor) {
    this.valor = valor;
  }


  public ResponseScoreScore razones(@javax.annotation.Nullable List<String> razones) {
    this.razones = razones;
    return this;
  }

  public ResponseScoreScore addRazonesItem(String razonesItem) {
    if (this.razones == null) {
      this.razones = new ArrayList<>();
    }
    this.razones.add(razonesItem);
    return this;
  }

  /**
   * Get razones
   * @return razones
   */
  @javax.annotation.Nullable
  public List<String> getRazones() {
    return razones;
  }

  public void setRazones(@javax.annotation.Nullable List<String> razones) {
    this.razones = razones;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseScoreScore responseScoreScore = (ResponseScoreScore) o;
    return Objects.equals(this.nombreScore, responseScoreScore.nombreScore) &&
        Objects.equals(this.valor, responseScoreScore.valor) &&
        Objects.equals(this.razones, responseScoreScore.razones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreScore, valor, razones);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseScoreScore {\n");
    sb.append("    nombreScore: ").append(toIndentedString(nombreScore)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    razones: ").append(toIndentedString(razones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("nombreScore", "valor", "razones"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseScoreScore
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseScoreScore.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseScoreScore is not found in the empty JSON string", ResponseScoreScore.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseScoreScore.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseScoreScore` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nombreScore") != null && !jsonObj.get("nombreScore").isJsonNull()) && !jsonObj.get("nombreScore").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreScore` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreScore").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("razones") != null && !jsonObj.get("razones").isJsonNull() && !jsonObj.get("razones").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `razones` to be an array in the JSON string but got `%s`", jsonObj.get("razones").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseScoreScore.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseScoreScore' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseScoreScore> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseScoreScore.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseScoreScore>() {
           @Override
           public void write(JsonWriter out, ResponseScoreScore value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseScoreScore read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseScoreScore given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseScoreScore
   * @throws IOException if the JSON string is invalid with respect to ResponseScoreScore
   */
  public static ResponseScoreScore fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseScoreScore.class);
  }

  /**
   * Convert an instance of ResponseScoreScore to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

